# Generated by Django 4.0.5 on 2022-06-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profileimg',
            new_name='avatar',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id_user',
        ),
    ]
