# Generated by Django 4.0.5 on 2022-06-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
