# Generated by Django 4.0.5 on 2022-06-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='post_id',
        ),
    ]
