# Generated by Django 4.0.5 on 2022-06-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_post_comment_post_id_rename_post_like_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
