# Generated by Django 4.0.5 on 2022-06-08 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_like_post_id_alter_like_user_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.IntegerField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
